name: the_revelation_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  audioplayers: ^6.5.1
  permission_handler: ^11.3.1
  flutter_html: ^3.0.0-beta.2
  youtube_player_flutter: ^9.1.3
  shared_preferences: ^2.2.2
  http: ^1.1.0
  flutter_tts: ^3.8.5
  wakelock_plus: ^1.1.4
  syncfusion_flutter_pdfviewer: ^28.1.33
  flutter_foreground_task: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/new_song.txt
    - assets/prayer.txt
    - assets/교독문.txt
    - assets/mybible/nrkv_bible.db
    - assets/mybible/foreign_bible.db
    - assets/mybible/general_bible.db
    - assets/mybible/strong.dct.mybible
    - assets/img/button/
    - assets/img/new_song/
    - assets/mybible/HokmahKor.cmt.mybible
    - assets/img/bible_map/
    - assets/img/app_icon.png
    - assets/Chapter/
    - assets/7Churches/
    - assets/12creed_Catechism.pdf
    - assets/img/prophet.jpg
    - assets/img/kings_juda_northisrael.jpg
    - assets/img/genealogy.png
